from collections.abc import Iterator
from typing import overload

class SelectorError(ValueError): ...
class ParseTimeout(TimeoutError): ...

class Node:
    @property
    def text(self) -> str: ...
    @property
    def tag(self) -> str | None: ...
    @property
    def attrs(self) -> dict[str, str]: ...
    def attr(self, name: str) -> str | None: ...
    def css(self, query: str) -> Selection: ...

class Selection:
    @overload
    def get(self) -> str | None: ...
    @overload
    def get(self, default: str) -> str: ...
    def getall(self) -> list[str]: ...
    def css(self, query: str) -> Selection: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node | str: ...
    def __iter__(self) -> Iterator[Node | str]: ...

def parse(html: str, timeout: float | None = None) -> Node: ...

class Response:
    @property
    def url(self) -> str: ...
    @property
    def status(self) -> int: ...
    @property
    def version(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    @property
    def body(self) -> bytes: ...
    def text(self) -> str: ...
    def parse(self, timeout: float | None = None) -> Node: ...

class Fetcher:
    def __init__(
        self,
        profile: str = "chrome",
        proxy: str | None = None,
        timeout: float = 30.0,
        verify: bool = True,
    ) -> None: ...
    async def get(self, url: str, headers: list[tuple[str, str]] | None = None) -> Response: ...
    def get_blocking(self, url: str, headers: list[tuple[str, str]] | None = None) -> Response: ...
